kartanu/backoffice/urls.py
from django.urls import path, include
from .views import *

app_name = "backoffice"
urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('user', users, name='users'),
    path('add-user/', add_user, name='add_user'),
    path('<int:id>/edit/', edit_user, name='edit_user'),
    path('<int:id>/preview/', user_preview, name='user_preview'),
    path('login/', login_view, name='login'),
    path('log-out/', log_out, name='log_out'),
    path('bayi', bayi, name='bayi'),
    path('balita', balita, name='balita'),
    path('remaja', remaja, name='remaja'),
    path('lansia', lansia, name='lansia'),
    path('ibu-hamil', hamil, name='hamil'),
    path('ibu-menyusui', menyusui, name='menyusui'),
    path('export-csv', export_csv, name='export_csv'),
    path("change-password", change_password, name="change_password"),
    path("<int:id>/delete", delete, name="delete"),
]

kartanu/frontend/urls.py
# from django.urls import path
# from .views import *

# app_name = "frontend"
# urlpatterns = [
#     path('', index, name='index'),
#     path('post-formulir/', post_formulir, name='post_formulir'),
# ]

kartanu/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url

from kartanu.apps.kecamatan.models import Kecamatan
from kartanu.apps.kelurahan.models import Kelurahan
from kartanu.apps.kabupaten.models import Kabupaten
from kartanu.backoffice.autocomplete import (
    KecamatanAutocomplete,
    KelurahanAutocomplete,
    KabupatenAutocomplete,
)


admin.site.site_header = "kartanu Admin"
admin.site.site_title = "kartanu Admin Portal"
admin.site.index_title = "Welcome to kartanu Admin Portal"

urlpatterns = [
    path('my-admin/', admin.site.urls),
    path('', include('kartanu.backoffice.urls', namespace='backoffice')),
    url("kabupaten-autocomplete/$", KabupatenAutocomplete.as_view(model=Kabupaten),
        name='kabupaten-autocomplete',),
    url("kecamatan-autocomplete/$", KecamatanAutocomplete.as_view(model=Kecamatan),
        name='kecamatan-autocomplete',),
    url("kelurahana-utocomplete/$", KelurahanAutocomplete.as_view(model=Kelurahan),
        name='kelurahan-autocomplete',),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# di server saat settings debug true
if settings.DEBUG:
    urlpatterns + static(settings.STATIC_URL,
                         document_root=settings.STATIC_ROOT)

kartanu/apps/kabupaten/models.py
from django.db import models

# Create your models here.


class Kabupaten(models.Model):
    code = models.IntegerField(null=True, default=0)
    name = models.CharField(max_length=50)
    provinsi = models.ForeignKey('provinsi.Provinsi', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

kartanu/apps/kecamatan/models.py
from django.db import models


class Kecamatan(models.Model):
    name = models.CharField(max_length=254)
    code = models.IntegerField(null=True, default=0)
    kabupaten = models.ForeignKey('kabupaten.Kabupaten', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

kartanu/apps/kelurahan/models.py
from django.db import models
# Create your models here.


class Kelurahan(models.Model):
    name = models.CharField(max_length=254)
    code = models.CharField(max_length=20, null=True, default="0")
    kecamatan = models.ForeignKey(
        'kecamatan.Kecamatan', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

kartanu/apps/provinsi/models.py
from django.db import models


class Provinsi(models.Model):
    name = models.CharField(max_length=50)
    code = models.IntegerField(null=True, default=0)

    def __str__(self):
        return self.name

kartanu/apps/user/models.py
import random
import string
import uuid
from datetime import date, datetime, timedelta

from django.apps.registry import apps
from django.contrib.auth.models import (AbstractBaseUser, PermissionsMixin,
                                        UserManager)
from django.conf import settings
from django.db import models
from django.db.models import Q
from django.utils import timezone
from kartanu.core.utils import FilenameGenerator
from kartanu.core.middleware import get_kecamatan_id, check_is_superuser, is_login
from kartanu.apps.kabupaten.models import Kabupaten
from kartanu.apps.provinsi.models import Provinsi

from model_utils import Choices
from sequences import get_next_value


class CustomUserManager(UserManager):
    def create_user(self, username, password, **extra_fields):
        now = timezone.now()
        user = self.model(
            username=username,
            is_active=True, is_superuser=False,
            last_login=now,  **extra_fields)

        if password:
            user.set_password(password)
        user.save(using=self._db)

        return user

    def create_superuser(self, username, password, **extra_fields):
        user = self.create_user(username, password, **extra_fields)
        user.is_staff = True
        user.is_active = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


    def get_queryset(self):
        return super(CustomUserManager, self).get_queryset().filter(
            is_active=True
        )


class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=50, unique=True, db_index=True)
    name = models.CharField(max_length=50, null=True)
    mother_name = models.CharField(max_length=50, null=True)
    nik = models.CharField(max_length=50, unique=True, null=True)
    is_active = models.BooleanField('active', default=True)
    is_staff = models.BooleanField('Status Staff', default=False)
    provinsi = models.ForeignKey(
        'provinsi.Provinsi', on_delete=models.PROTECT, blank=True, null=True)
    kabupaten = models.ForeignKey(
        'kabupaten.Kabupaten', on_delete=models.PROTECT, blank=True, null=True)
    kecamatan = models.ForeignKey(
        'kecamatan.Kecamatan', on_delete=models.PROTECT, null=True)
    kelurahan = models.ForeignKey(
        'kelurahan.Kelurahan', on_delete=models.PROTECT, null=True)
    rt = models.CharField(max_length=50, blank=True, null=True)
    rw = models.CharField(max_length=50, blank=True, null=True)
    mobile_number = models.CharField(max_length=30, default='', blank=True)
    picture = models.ImageField(upload_to=FilenameGenerator(prefix='user'), default='', blank=True)
    ktp = models.ImageField(upload_to=FilenameGenerator(prefix='user'), default='', blank=True)
    place_of_birth = models.CharField(max_length=50, null=True)
    from_web = models.BooleanField(default=False)
    dob = models.DateField(blank=True, null=True)
    GENDER = Choices(("L", "Laki Laki"), ("P", "Perempuan"))
    gender = models.CharField(
        max_length=10, choices=GENDER)
    MARITAL_STATUS = Choices(("Kawin", "Kawin"), ("Lajang", "Lajang"))
    marital_status = models.CharField(
        max_length=10, choices=MARITAL_STATUS, default="Lajang")
    job = models.CharField(max_length=20, blank=True, null=True)
    age_year = models.DecimalField(max_digits=50, decimal_places=2,  default=0)
    age_month = models.DecimalField(max_digits=50, decimal_places=2, default=0)
    age_string = models.CharField(max_length=250, null=True)
    EDUCATION = Choices(
        ("SD", "SD"),
        ("SMP", "SMP"),
        ("SLTP", "SLTP"),
        ("SMA", "SMA"),
        ("SLTA", "SLTA"),
        ("D3", "D3"),
        ("S1", "S1"),
        ("S2", "S2"),
        ("S3", "S3"),
        ("Lainnya", "Lainnya")
    )
    education = models.CharField(max_length=255, blank=True, null=True, choices=EDUCATION)
    order = models.IntegerField(default=0, blank=True)
    print_counter = models.IntegerField(default=0)
    is_pregnant = models.BooleanField('is_pregnant', default=False)
    is_breeding = models.BooleanField('is_breeding', default=False)
    parent = models.ForeignKey('User', on_delete=models.CASCADE, null=True)

    USERNAME_FIELD = 'username'
    objects = CustomUserManager()

    class Meta:
        verbose_name = 'user'
        verbose_name_plural = 'users'

    def __str__(self):
        return '%s - %s' % (self.username, self.name)

    def __unicode__(self):
        return self.name or self.username or 'User #%d' % (self.id)
    
    def calculate_age(self):
        if not self.dob:
            return 0
        today = date.today()
        born = self.dob
        try: 
            birthday = born.replace(year=today.year)
        except ValueError: # raised when birth date is February 29 and the current year is not a leap year
            birthday = born.replace(year=today.year, month=born.month+1, day=1)
        if birthday > today:
            return today.year - born.year - 1
        else:
            return today.year - born.year
    
    def calculate_month(self):
        if not self.dob:
            return 0
        today = date.today()
        born = self.dob
        time_difference = today - born
        D = time_difference.days
        M = int((D/365)*12)
        return M

    def save(self, *args, **kwargs):
        self.age_month = self.calculate_month()
        self.age_year = self.calculate_age()

        if self.age_month:
            self.age_string = f"{self.age_year} th, {self.age_month - self.age_year * 12} bln"  
        else:
            self.age_string = "0th, 0bln"
                  
        super(User, self).save(*args, **kwargs)

    # def save(self, *args, **kwargs):
    #     exist_id = self.id
    #     super(User, self).save(*args, **kwargs)
    #     self.kabupaten = Kabupaten.objects.first()
    #     self.provinsi = Provinsi.objects.first()
    #     if not exist_id:
    #         self.order = get_next_value("order_user")
    #         last_counter = get_next_value(self.kelurahan.code) + 1
    #         self.id_card_number = f"{self.kelurahan.code}-{str(last_counter).zfill(5)}"
    #         PrintCard.objects.create(user=self, order=self.order)
    #     self.save()


class PrintCard(models.Model):
    user = models.ForeignKey(
        'user.User', on_delete=models.CASCADE, unique=True)
    order = models.IntegerField(default=0)

kartanu/backoffice/forms.py
from django import forms
from django.contrib import auth
from django.forms.forms import BaseForm
from dal import autocomplete
from kartanu.apps.user.models import User
import uuid


class BaseUserForm(forms.ModelForm):
    nik = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control'}), required=False)
    username = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control'}), required=False)
    password = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control'}), required=False)
    place_of_birth = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control'}))
    dob = forms.DateField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'type':'date'}))
    name = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', }))
    gender = forms.ChoiceField(widget=forms.Select(
        attrs={'class': 'form-control'}), choices=[("L", "Laki2"), ("P", "Perempuan")])
    
    class Meta:
        model = User
        fields = (
            'name',
            'nik',
            'gender',
            'dob',
            'place_of_birth',
            'kabupaten',
            'kecamatan',
            'kelurahan',
            'rt',
            'rw',
            'is_pregnant',
            'is_breeding',
            'is_staff',
            'username',
            'password'
        )
        widgets = {
            'kabupaten': autocomplete.ModelSelect2(url='kabupaten-autocomplete', forward=('provinsi',), attrs={'data-placeholder': 'Pilih Kabupaten', 'class': 'form-control', 'required': True},),
            'kecamatan': autocomplete.ModelSelect2(url='kecamatan-autocomplete', forward=('kabupaten',), attrs={'data-placeholder': 'Pilih Kecamatan', 'class': 'form-control', 'required': True},),
            'kelurahan': autocomplete.ModelSelect2(url='kelurahan-autocomplete', forward=('kecamatan',), attrs={'data-placeholder': 'Pilih Kelurahan', 'class': 'form-control', 'required': True}),
        }
        # initial_fields = ['kecmatan']

    def __init__(self, *args, **kwargs):
        super(BaseUserForm, self).__init__(*args, **kwargs)

    
    def clean_username(self):
        username = self.cleaned_data['username']
        if not username or username == "None":
            username = uuid.uuid4().hex[:30]
        return username


class UserCreateForm(BaseUserForm):

    def __init__(self, *args, **kwargs):
        super(UserCreateForm, self).__init__(*args, **kwargs)


    def save(self, *args, **kwargs):
        user = super(UserCreateForm, self).save(*args, **kwargs)
        
        username = self.cleaned_data['username']
        if not username or username == "None":
            user.username = uuid.uuid4().hex[:30]

        if self.cleaned_data['password']:
            user.set_password(self.cleaned_data['password'])

        user.save()
        return user


# class UserEditForm(BaseUserForm):

#     def __init__(self, *args, **kwargs):
#         super(UserEditForm, self).__init__(*args, **kwargs)
#         self.user = kwargs['instance']

#     def save(self, *args, **kwargs):
#         self.user.save()
#         return self.user


class LoginForm(auth.forms.AuthenticationForm):
    username = forms.CharField(max_length=30)
    password = forms.CharField(max_length=30)

    def clean(self):
        return super(LoginForm, self).clean()

kartanu/frontend/forms.py
# from django import forms

# from kartanu.apps.dealer.models import Dealer
# from kartanu.apps.formulir.models import Formulir
# from kartanu.apps.product.models import Product
# from kartanu.apps.serial_number.models import SerialNumber


# class FormulirForm(forms.ModelForm):
#     dealer_code = forms.CharField(required=False)

#     class Meta:
#         model = Formulir
#         fields = "__all__"
#         exclude = ("status",)

#     def clean_serial_number(self):
#         serial_number = self.cleaned_data.get("serial_number", False)
#         serial = SerialNumber.objects.filter(serial_number=serial_number)
#         if not serial.first():
#             raise forms.ValidationError("Serial Number tidak ditemukan")
#         elif serial.first().status == 'redeem':
#             raise forms.ValidationError("Serial Number sudah digunakan")
#         return serial_number

#     #  def clean_dealer_code(self):
#     #     code = self.cleaned_data.get("dealer_code", False)
#     #     if code and not Dealer.objects.filter(code=code).first():
#     #         raise forms.ValidationError("Kode Dealer tidak ditemukan")
#     #     return code

#     def clean(self):
#         cleaned_data = super(FormulirForm, self).clean()
#         if self.errors:
#             return cleaned_data

#         serial_number = self.cleaned_data['serial_number']
#         dealer_code = self.cleaned_data['dealer_code']
#         if serial_number[0].lower() == 'd':
#             if not dealer_code:
#                 raise forms.ValidationError("Kode dealer wajib diisi untuk qrcode ini")
#             elif not Dealer.objects.filter(code=dealer_code).first():
#                 raise forms.ValidationError("Kode Dealer tidak ditemukan")

#         return cleaned_data

#     def save(self, commit=True):
#         formulir = super(FormulirForm, self).save()
#         SerialNumber.objects.filter(serial_number=formulir.serial_number).update(status='redeem')
#         return formulir

kartanu/apps/user/views.py
from django.shortcuts import render

# Create your views here.

kartanu/frontend/views.py
# from django.http import JsonResponse
# from django.template.response import TemplateResponse
# from django.views.decorators.csrf import csrf_exempt

# from kartanu.apps.formulir.models import Formulir

# from .forms import FormulirForm


# def index(request):
#     form = FormulirForm(data=request.POST or None)
#     context = {
#         "form": form,
#     }
#     return TemplateResponse(request, "frontend/index.html", context)


# @csrf_exempt
# def post_formulir(request):
#     if request.is_ajax and request.method == "POST":
#         form = FormulirForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return JsonResponse({"message": "sukses"}, status=200)
#         else:
#             return JsonResponse(form.errors, status=400)
#     return JsonResponse({"error": "error gk jelas hehe"}, status=400)

kartanu/templates/backoffice/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
    <title>{% block title %} {% endblock %}</title>
    {% block extra_header %} {% endblock %}

    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700" rel="stylesheet">
    <link href="{% static 'css/trackpad-scroll-emulator.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/chartist.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/jquery.raty.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fonts/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/nouislider.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/explorer.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/sweetalert2.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/loading.css' %}" rel="stylesheet" type="text/css">
    <!-- <link href="/static/autocomplete_light/select2.css" rel="stylesheet" type="text/css"> -->
    {% comment %} <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.ico'%}"> {% endcomment %}
  </head>
  <body class="">
    <div class="admin-wrapper">
      <div class="admin-sidebar">
        <div class="admin-sidebar-header">
          <div class="admin-sidebar-logo">
            <a href="/">
              <!-- <img src="{% static 'img/logo/logo.png' %}" class="svg" alt="Home"> -->
            </a>
            {% comment %} <a href="/" class="admin-sidebar-logo-title">
              <strong></strong>
              <span>------------------------------------</span>
            </a> {% endcomment %}
          </div>
          <!-- /.admin-sidebar-logo -->
        </div>
        <!-- /.admin-sidebar-header -->
        <div class="admin-sidebar-content">
          <h3>Menu</h3>
          <ul class="nav flex-column">
            <li class="nav-item">
                <a href="{% url 'backoffice:dashboard' %}" class="nav-link {% if request.resolver_match.view_name == 'backoffice:dashboard'  %} active {% endif %}">
                  <i class="fa fa-tachometer"></i><span>Laporan</span>
                </a>
            </li>
          </ul>

          <ul class="nav flex-column">
            <li class="nav-item">
                <a href="{% url 'backoffice:bayi' %}" class="nav-link {% if request.resolver_match.view_name == 'backoffice:bayi'  %} active {% endif %}">
                  <i class="fa fa-user"></i><span>Data Bayi</span>
                </a>
            </li>
          </ul>


          <ul class="nav flex-column">
            <li class="nav-item">
                <a href="{% url 'backoffice:balita' %}" class="nav-link {% if request.resolver_match.view_name == 'backoffice:balita'  %} active {% endif %}">
                  <i class="fa fa-user"></i><span>Data Balita</span>
                </a>
            </li>
          </ul>


          <ul class="nav flex-column">
            <li class="nav-item">
                <a href="{% url 'backoffice:remaja' %}" class="nav-link {% if request.resolver_match.view_name == 'backoffice:remaja'  %} active {% endif %}">
                  <i class="fa fa-user"></i><span>Data Remaja</span>
                </a>
            </li>
          </ul>

          <ul class="nav flex-column">
            <li class="nav-item">
                <a href="{% url 'backoffice:lansia' %}" class="nav-link {% if request.resolver_match.view_name == 'backoffice:lansia'  %} active {% endif %}">
                  <i class="fa fa-user"></i><span>Data Lansia</span>
                </a>
            </li>
          </ul>

          <ul class="nav flex-column">
            <li class="nav-item">
                <a href="{% url 'backoffice:hamil' %}" class="nav-link {% if request.resolver_match.view_name == 'backoffice:hamil'  %} active {% endif %}">
                  <i class="fa fa-user"></i><span>Ibu Hamil</span>
                </a>
            </li>
          </ul>

          <ul class="nav flex-column">
            <li class="nav-item">
                <a href="{% url 'backoffice:menyusui' %}" class="nav-link {% if request.resolver_match.view_name == 'backoffice:menyusui'  %} active {% endif %}">
                  <i class="fa fa-user"></i><span>Ibu Menyusui</span>
                </a>
            </li>
          </ul>


          <ul class="nav flex-column">
            <li class="nav-item">
                <a href="{% url 'backoffice:users' %}" class="nav-link {% if request.resolver_match.view_name == 'backoffice:users'  %} active {% endif %}">
                  <i class="fa fa-user"></i><span>Semua Data</span>
                </a>
            </li>
          </ul>



        </div>
        <!-- /.admin-sidebar-content -->
        <div class="admin-sidebar-footer">
          <strong></strong>
          <span>&copy;  Brebes</span>
        </div>
        <!-- /.admin-sidebar-footer -->
      </div>
      <!-- /.admin-sidebar -->
      <div class="admin-main">
        <div class="admin-header">
          <div class="container-fluid">
            <!-- <div class="admin-header-sidebar-toggle toggle">
              <span></span>
              <span></span>
              <span></span>
            </div> -->
            <div class="admin-header-avatar">
              <span class="avatar" style="background-image: url({% static 'images/user.png' %})"></span>
              <span class="admin-header-avatar-name">{{ request.user.name }}<i class="fa fa-chevron-down"></i></span>
              <ul class="admin-header-avatar-menu">
                <li><a href="#">{{ request.user.name }}</a></li>
                <li><a href="{% url 'backoffice:change_password' %}">Ganti Password</a>Ganti</li>
                <li><a href="{% url 'backoffice:log_out' %}">Keluar</a></li>
              </ul>
              <!-- /.admin-header-avatar-menu -->
            </div>
            <!-- /.admin-header-actions -->
          </div>
          <!-- /.container -->
        </div>
        <!-- /.admin-header -->
        <div class="admin-content">
          <div class="container">
            {% block content %} {% endblock %}
            <!-- /.box -->
          </div>
          <!-- /.container -->
        </div>
        {% block footer %}
        <!-- /.admin-content -->
        <div class="admin-footer">
          <div class="container-fluid">
            <div class="row">
              <div class="col-sm-6">

              </div>
              <!-- /.col-* -->
            </div>
            <!-- /.row -->
          </div>
          <!-- /.container-fluid -->
        </div>
        {% endblock %}
      </div>
      <!-- /.admin-main -->
    </div>
    <!-- /.admin-wrapper -->

    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <!-- <script type="text/javascript" src="{% static 'js/tether.min.js' %}"></script> -->
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- <script type="text/javascript" src="{% static 'js/chartist.min.js' %}"></script> -->
    <!-- <script type="text/javascript" src="{% static 'js/jquery.trackpad-scroll-emulator.min.js' %}"></script> -->
    <!-- <script type="text/javascript" src="{% static 'js/jquery.inlinesvg.min.js' %}"></script> -->
    <!-- <script type="text/javascript" src="{% static 'js/jquery.affix.js' %}"></script> -->
    <!-- <script type="text/javascript" src="{% static 'js/jquery.scrollTo.js' %}"></script> -->
    <!-- <script type="text/javascript" src="{% static 'js/nouislider.min.js' %}"></script> -->
    <!-- <script type="text/javascript" src="{% static 'js/jquery.raty.js' %}"></script> -->
    <!-- <script type="text/javascript" src="{% static 'js/wNumb.js' %}"></script> -->
    <!-- <script type="text/javascript" src="{% static 'js/explorer.js' %}"></script> -->
    <!-- <script type="text/javascript" src="{% static 'js/sweetalert2.min.js' %}"></script> -->

    <script type="text/javascript">
      $(document).ready(function(){
        $(".delete").on('click', function(e) {
        e.preventDefault();
        swal({
          text: "Apakah anda yakin ?",
          cancelButtonColor: '#d33',
          showCancelButton: true,
          type: "info",
          customClass: 'swal-wide',
          confirmButtonColor: 'green',
          confirmButtonText: 'Yes'
          }).then((result) => {
              if (result.value) {
                window.location.href = this.getAttribute('href');
              } else {
                e.preventDefault();
                return false
              }
          })
        })
      })
    </script>
    {% block script %}
    {% endblock %}
  </body>
</html>

kartanu/templates/backoffice/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700" rel="stylesheet">
    <link href="{% static 'css/trackpad-scroll-emulator.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/chartist.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/jquery.raty.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fonts/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/nouislider.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/explorer.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/ico/sahabatelvine.ico'%}">
    <title>Login - Explorer</title>
  </head>
  <body class="">
    <div class="page-wrapper">
      <div class="main-wrapper">
        <div class="main">
            <div class="container" style="text-align: center; margin-top: 5%;">
              <div class="row" style="margin-top: 40px;">
                
                <div class="col-sm-4 offset-sm-4">
                  
                  <h2 >BANK DATA BIDAN</h2>
                  <h3 class="page-title-small">Login </h1>
                  
                  <form method="post" action="{% url 'backoffice:login'%}">
                    {% csrf_token %}
                    <div class="form-group">
                      <label for="login-form-email">Username</label>
                      <input type="text" name="username" class="form-control" autofocus="" required="" id="id_username">                    </div>
                      {{ auth_form.username.errors }}
                      <!-- /.form-group -->
                    <div class="form-group">
                      <label for="login-form-password">{{ auth_form.password.label }}</label>
                      <input type="password" class="form-control" name="password" required="" id="id_password">                    </div>
                      {{ auth_form.password.errors }}
                      <!-- /.form-group -->

                      {% if auth_form.non_field_errors %}
                          {% for error in auth_form.non_field_errors %}
                              <p>{{ error }}</p>
                          {% endfor %}
                      {% endif %}

                    <button type="submit" class="btn btn-primary pull-right">Login</button>
                  </form>
                </div>
                <!-- /.col-sm-4 -->
              </div>
              <!-- /.row -->
            <!-- /.container-fluid -->
          </div>
        <!-- /.main -->
      </div>
      <!-- /.main-wrapper -->
    <!-- /.side-wrapper -->
      <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
      <script type="text/javascript" src="{% static 'js/particles.min.js' %}"></script>
      <script>
          var el = $('#particle-js');
          if (el.length) {
              particlesJS.load('particle-js', '{% static "json/particles.json" %}', function() {});
          }
      </script>
    </body>
</html>